document.addEventListener("DOMContentLoaded", function () {

    // Questions partially extracted from Letterloop: https://www.letterloop.co/questions.

    const questions = [
        "What is the meaning of life?",
        "What is your biggest dream?",
        "What is your favorite book and why?",
        "What motivates you to succeed?",
        "What is your definition of happiness?",
        "What's something people often incorrectly assume about you?",
        "What character traits do you most appreciate in your teammates?",
        "Some historical figures have epithets attached to their names (e.g. Alexandar The Great or Michael Jackson: King of Pop). What would you like yours to be?",
        "Is there any great memory that you want to share today?",
        "Which new skills have you developed at your job this year?",
        "What was a pivotal moment in your career that led you to where you are now?",
        "What does your ideal/dream life look like?",
        "What's something you are really into right now?",
        "Have your ever made a cooking disaster or a meal that turned out really badly?",
        "If you could try out any other profession for a day what would it be?",
        "If you could pick a new first name for yourself what name would you choose and why?",
        "Who in life has inspired you the most?",
        "What's a funny or interesting story from your week?",
        "Imagine you could bring drawings to life; what’s the first thing you would draw?",
        "Think of the best teacher you've ever had. What did they teach and what made them so special?",
        "A highly advanced alien species has arrived on Earth and you are selected as the spokesperson to represent humanity. You have one sentence to communicate your most important message. What do you say?",
        "What's the best outcome of a serendipitous event you've experienced in your life?",
        "Would you rather have the power to turn invisible or to read minds?",
        "What is something you never thought you'd be able to do until you actually did it?",
        "What's something people are surprised to learn about you?",
        "Imagine you woke up with the ability to speak every language fluently; how would you use this power first?",
        "What do you believe is the most significant factor in shaping one's destiny and how much control does one have over it?",
        "Do you have an inner monologue? Do you think your thoughts in words or concepts?",
        "What's a habit you picked up as a child that you wish you hadn't?",
        "What's one thing you wish you had known when you started your career?",
        "If you could pick up a new skill in an instant what would it be?",
        "What do you find yourself fantasizing about these days?",
        "What's one thing about you that hasn't changed in the last 10 years?",
        "What's one thing you do to distract yourself that you think you should less of?",
        "What's a truth you've recently come to terms with?",
        "What would you like to achieve during the next year on your career?",
        "What activity absorbs you completely and makes you lose track of time?",
        "What fictional character do you most relate to?",
        "What are you most proud of right now?",
        "What gives you supreme joy right now?",
        "If you were a dictator of a small country what crazy dictator things would you do?",
        "If you could choose one experience from your life that your child could also have what would it be?",
        "What's something you're looking forward to in the coming months?",
        "What’s is one thing we don’t know about you?",
        "What's a surprising hobby you enjoy?",
        "What's something that will never cease to make you laugh?",
        "What’s your best tip for staying focused and productive?",
        "What's a challenge you recently faced?",
        "You can go back in time and experience any historical event. Where do you go and when?",
        "What does 'success' mean to you and how has that definition evolved over time?",
        "If you could live in any movie universe for a week which one would you pick?",
        "What kind of a day have you had so far today?",
        "What's one rule you'd put in place if you ruled the world for a day?",
        "Do you want to share a personal goal that you have?",
        "What's the most useless thing you've ever been taught in school?",
        "If you could create a new holiday what would it celebrate?",
        "Is there anything you think your generation does better than the next generation?",
        "Which form of self-expression has become increasingly important to you?",
        "If all animals were the same size what would win in a fight?",
        "What's a deep question you often ask yourself?",
        "What makes you optimistic about the future?",
        "What's a goal or project you've made progress on?",
        "What compliment would you give yourself right now?",
        "What would brighten your day today?",
        "What recent mistake taught you the most?",
        "What's your least favorite part of your job and why?",
        "When do you feel most helpful to others?",
        "Have you ever had a mentor and what was the most important thing they taught you?",
        "Where do you feel you're improving the most?",
        "What's your favorite article of clothing you own?",
        "What do you feel like you’re really good at?",
        "What scientific or technological advance blows your mind?",
        "What would people be surprised to learn you spend a lot of time on at work?",
        "Which best describes you? An introvert or an extrovert?",
        "What's one thing you would change that's commonly taught to children today?",
        "What do you consider as red flags in a potential employee or coworker?",
        "You just became a new member of the Spice Girls. What's Spice name do you create for yourself?",
        "What's something expensive you splurge on that you believe is worth the money?",
        "What's the most significant risk you've taken in your career and how did it turn out?",
        "What do you think is the most important quality of human civiliation for its continued survival?",
        "What title would you give to the current chapter of your life?",
        "What legacy do you hope to leave as a result of your professional work?",
        "What's a recent personal growth moment you've experienced?",
        "What do you know isn't real but really wish it existed?",
        "If you were an inanimate object what would you be and why?",
        "What behavior or trait immediately makes you like someone?",
        "What's your favorite personality or character trait about yourself?",
        "What is the most fun you have had recently?",
        "What's your go-to productivity hack?",
        "What talent of yours do you consider to be inherent like an advantage you were born with?",
        "Is there anything you think your generation does better than the previous generation?",
        "What's a habit you'd like to adopt but find difficult to stick to?",
        "You can stop time for 24 hours. What do you do with this opportunity?",
        "How can we contribute to a positive work environment or culture?",
        "What kind of games did you play as a child?",
        "Who had the most significant impact on your career and why?",
        "If you could learn one secret from anyone who would it be and what would it pertain to?",
        "What's a current trend you find concerning?",
        "What's the best purchase you recently made?",
        "What were some of your most challenging learning moments in your career and what made them so?",
        "What is the one thing you've made that you're the most proud of?",
        "Do you feel challenged enough at work?",
        "What elements of your daily routine have become non-negotiable lately?",
        "If you had to give a TED Talk without any preparation what topic would you choose?",
        "What's the weirdest food combination you actually enjoy?",
        "What's something you admire about your colleagues?",
        "What's something you came across recently that gave you hope or inspiration?",
        "What would you like to learn more about soon?",
        "What's one new and interesting thing you've been thinking about lately?",
        "What's something you're looking forward to experiencing or doing?",
        "What's something you learned recently?",
        "What's something you wish people asked you about more often?",
        "What would you most like to become famous for?",
        "What's your favorite snack?",
        "What's one thing you did recently that you're proud of?",
        "What's an unconventional piece of advice that has had a significant impact on your life?",
        "What has surprised you recently?",
        "What advice would you give to your teenage self?",
        "What is the most trivial thing about which you have a strong opinion?",
        "What do you plan to learn in the coming days?",
        "What’s one thing that brings you energy and joy lately?",
        "If you could travel anywhere in the world right now where would you go and why?",
        "Do you think you fit a particular stereotype? Which one and why?",
        "What’s one thing you hope to get accomplished soon?",
        "If you were reincarnated as an animal based on your personality what animal do you think you would come back as?",
        "What's your mantra lately?",
        "What's the best thing that happened to you recently?",
        "What is something you're terrible at but wish you could do well?",
        "What’s your strategy for professional growth?",
        "What is something you recently tried and loved?",
        "What's a book or podcast you'd recommend that’s related to your career?",
        "What's the best advice you've ever received?",
        "What's the most useful thing you've ever been taught in school?",
        "What's something you recently learned?",
        "What’s something you are really into right now?",
        "If you could have a superpower that helps you in your current job what would it be?",
        "What's your favorite way to unwind after a busy week?",
        "What's a hobby you've always wanted to try?",
        "What aspects of life are you loving most right now?",
        "What is something you love that everyone else hates?",
        "What areas of personal development do you feel you need to focus on to to achieve further professional success?",
        "If you could witness any event from the past present or future what would it be and why?",
        "What's something you're you proud of but never have an excuse to talk about?",
        "What's one work-related skill you'd like to develop and why?",
        "What would you consider to be a 'dream job' and how close is your current job to that ideal?",
        "What is something you hate that everyone else loves?",
        "What are your best habits? How did you develop them?",
        "What would you like to thank yourself for right now?",
        "How do you stay productive and motivated when working from home?",
        "How would you describe your approach to your career so far?",
        "What are people surprised to learn you're really good at?",
        "How do you stay updated with the latest developments in your field?",
        "What's your favorite lesson you've learned from a culture different from your own?",
        "Which childhood book or story influenced you the most?",
        "What's your favorite way to relax these days?",
        "What’s your take on the common career advice to 'follow your passion'",
        "What's a recent disagreement or conflict you had in the workplace? How did you handle it?",
        "What's a recent decision you're glad you made?",
        "What is something you've become increasingly interested in the more you've learned about it over time?",
        "What skill of yours are you most proud of?",
        "What's the best career advice you've ever received?",
        "Are human desires endless and can a society exist without wanting more?",
        "What is something you've done that you recommend everyone to do?",
        "Name one thing that stresses you out without fail.",
        "What's a new skill or knowledge you're learning right now?",
        "How has your perspective on work-life balance evolved over the years and what influences shaped this?",
        "Have any priorities recently shifted to the forefront of your life?",
        "You get to invent something. What is it and what does it do?",
        "What's a significant professional challenge you overcame in the last year?",
        "What do you think all happy people have in common?",
        "What's something other people commonly do that you avoid and are proud of doing so?",
        "What public figure has had greatest impact on your personal life philosophy?",
        "What's a common myth about your profession that you can debunk?",
        "What tools or apps do you find indispensable for your work?",
        "What's one thing you've never done but feels like it's something you need to do in your lifetime?",
        "What song has been on repeat for you lately? Does it have any special meaning?",
        "What made you happy today?",
        "What is your favorite word and why?",
        "What's your favorite quote and why?",
        "If you could only use three words how would you describe yourself?",
        "What professional accomplishment are you most proud of and why?",
        "You can only guarantee your child learns one life principle. What do you teach them?",
        "If every time you snapped your fingers you would instantly and irreversibly be transported to a random point in humanity's timeline would you snap your fingers? If so how often?",
        "What are 3 things you love about yourself?",
        "What's the most important life lesson you've learned in the last 10 years?",
        "What's something you're looking forward to doing or experiencing?",
        "What are you most grateful for in your life right now?",
        "What's a goal you're working towards?",
        "Explain your job to a 3 year old.",
        "What is one your core principles in life that is guiding you at this time?",
        "What’s something at the top of your to-do list?",
        "If the last month were a chapter of your life what would you title it?",
        "Is there anything you think the next generation will do better than your generation?",
        "What word describes your essence the best?",
        "What's something you wish you knew earlier about being a good colleague?",
        "Is there a quote or saying you call to mind often intentionally or unintentionally? ",
        "Have you ever desired or longed for something but once you got it discovered it was overrated or that you no longer wanted it?",
        "What trait signals to you that someone is wise?",
        "How has your perspective on your career changed over time?",
        "What’s a mantra or affirmation you resonate with right now?",
        "What's the most exciting improvement you've been seeing in yourself recently?",
        "What practice or habit (if anything) best supports your mental health/well-being?",
        "If you could be the CEO of any company what company would you choose?",
        "If you had to skip on meal every day for the rest of your life which meal would it be?",
        "What's something that you wish was easier for you?",
        "What's a new hobby or activity you've tried recently?",
        "If your life was a genre of music what would it be?",
        "What's something you're absolutely convinced is going to happen in the future?",
        "What's a fun project you've worked on recently?",
        "Which superpower would you pick to subtly make your everyday life easier?",
        "What is your biggest accomplishment outside of academia and work?",
        "Is there anything you think the previous generation did better than your generation?",
        "What are you grateful for lately?",
        "What fictional character would you most like to have as a mentor?",
        "What's one interesting thing you've been thinking about lately?",
        "Where were you born?",
        "What's something you're interested to learn more about?",
        "What's something that will make you smile every time?",
        "What subject or course do you wish they had offered in school?",
        "What's your biggest dream?",
        "What’s a new movie or show you've enjoyed recently?",
        "Does your current job challenge you to grow in the ways you truly want? If not what’s missing?",
        "What trends do you foresee in your industry in the next five years?",
        "How well do you receive feedback?",
        "What's your secret talent that no one would expect you to have?",
        "If you could choose one superpower but it had to be extremely specific and unusual what would it be?",
        "What skills or passions are you not currently utilizing in your job?",
        "What's a memorable lesson you've learned from a mistake you've made?",
        "If you could use a time machine would you rather have one that only goes back in time or only goes forward?",
        "If you could know for certain the answer to any question what would that question be?",
        "The world needs more of my...",
        "What is the most ordinary-seeming thing that you find fascinating?",
        "When you think of the legacy you want to leave does your current job contribute to that vision?",
        "What's a habit you're trying to develop or break?",
        "What is something that's easy for you but seems difficult for most other people?",
        "What's one of your biggest pet peeves?",
        "What's a major life decision you made that you're really happy about?",
        "On a scale of 1-10 how happy are you?",
        "What behavior or trait immediately makes you trust someone?",
        "How do you prioritize your tasks when everything seems urgent?",
        "Which superhero’s powers do you feel are underestimated?",
        "What color describes your mood today?",
        "What are 3 words you'd used to describe how you currently feel?",
        "What's one way in which you're completely different from yourself 10 years ago?",
        "Is there an experience you think everyone should have at least once in their lives?",
        "What's been on your mind a lot lately?",
        "How did you spend your most recent weekend?",
        "What do people think is hard but actually isnt?",
        "What's something you currently doubt conciously or subconsciously that you can do?",
        "If you were a teacher what would you teach and what ages would your students be?",
        "What is the last book you read? Would you recommend it?",
        "What is your most regretful purchase?",
        "If you could witness any event in the future what would you choose to see?",
        "You're given a sidekick with any superpower of your choosing. What's their name and what's their power?",
        "What first impression do you hope you make on people?",
        "What stopped you from following or encouraged you to follow your childhood passion?",
        "What’s your dream vacation right now? Why?",
        "How has your industry changed since you started your career?",
        "What's something you could talk about for hours right now?",
        "What self-limiting beliefs do you currently hold?",
        "What trait do you admire?",
        "What are the top three qualities of your ideal colleague?",
        "What is something other people admire about you?",
        "How do you think you'll be completely different from yourself 10 years from now?",
        "What's the most unusual food you've ever tried and would you eat it again?",
        "What's a skill you use at work that you also use in your personal life?",
        "If you had to get a tail what tail would you want and what would you use it for?",
        "What's something you recently came across that gave you hope or inspiration?",
        "What's something you did recently that took courage?",
        "What's a movie you can watch over and over without ever getting tired of?",
        "What do you think is the most significant impact individuals can make in the world today?",
        "What is the most memorable meal you've ever had? (It can be good or bad.) What made it so memorable?",
        "What's your philosophy in life?",
        "How do you describe your current job to someone who's not in your industry?",
        "Is there any proffesional breakthrough in your career?",
        "What's your earliest memory?",
        "What is your best season of the year? Why?",
        "What was your favorite childhood toy?",
        "Is there anything you would say to yourself in your early 20s?",
        "What is one action that would make today a success?",
        "Given the choice of anyone in the world whom would you want as a dinner guest?",
        "What do you think will still be the same about you 10 years from now?",
        "Have you been to any cool places lately?",
        "Are you known for having a personal catchphrase or something you say often?"
    ];

    function getRandomQuestion() {
        const randomIndex = Math.floor(Math.random() * questions.length);
        return questions[randomIndex];
    }

    const questionBox = document.getElementById("question-box");
    questionBox.textContent = getRandomQuestion();

    const calmColors = [
        "#E3F2FD", // light blue
        "#FFEBEE", // soft pink
        "#E8F5E9", // soft green
        "#FFF3E0", // light orange
        "#F3E5F5", // lavender
        "#E0F7FA", // light cyan
        "#FFFDE7"  // pale yellow
    ];

    function getRandomBackgroundColor() {
        const randomIndex = Math.floor(Math.random() * calmColors.length);
        return calmColors[randomIndex];
    }

    document.body.style.backgroundColor = getRandomBackgroundColor();
});
