document.addEventListener("DOMContentLoaded", function () {
    const questions = [
        "What is the meaning of life?",
        "What is your biggest dream?",
        "What is your favorite book and why?",
        "What motivates you to succeed?",
        "What is your definition of happiness?",
        "What's a belief you held strongly that you changed your mind about?",
        "What principle do you hold that you would never compromise on even under pressure?",
        "What's something people often incorrectly assume about you?",
        "How do you find balance between your personal and professional life?",
        "What character traits do you most appreciate in your teammates?",
        "Some historical figures have epithets attached to their names (e.g. Alexandar The Great or Michael Jackson: King of Pop). What would you like yours to be?",
        "What's one great memory you want to share?",
        "Have you picked up any new skills at your job this year?",
        "What was a pivotal moment in your career that led you to where you are now?",
        "How do you balance work and personal life?",
        "What does your ideal/dream life look like?",
        "How much of your decision to stay in your current job is influenced by comfort and fear versus ambition and fulfillment?",
        "What's something you are really into right now?",
        "Did your household ever have a cooking disaster or a meal that turned out really badly one time?",
        "If you could try out any other profession for a day what would it be?",
        "If you could pick a new first name for yourself what name would you choose and why?",
        "Who in life has inspired you the most?",
        "What's a funny or interesting story from your week?",
        "Imagine you could bring drawings to life; what’s the first thing you would draw?",
        "What's a challenge you've overcome that made you a stronger person?",
        "Think of the best teacher you've ever had. What did they teach and what made them so special?",
        "A highly advanced alien species has arrived on Earth and you are selected as the spokesperson to represent humanity. You have one sentence to communicate your most important message. What do you say?",
        "What's the best outcome of a serendipitous event you've experienced in your life?",
        "What's a compliment you recently received?",
        "Would you rather have the power to turn invisible or to read minds?",
        "What is something you never thought you'd be able to do until you actually did it?",
        "What do you wish people would stop talking about right now?",
        "What's something people are surprised to learn about you?",
        "What's the most bizarre dream you've ever had?",
        "Imagine you woke up with the ability to speak every language fluently; how would you use this power first?",
        "What do you believe is the most significant factor in shaping one's destiny and how much control does one have over it?",
        "What's the quirkiest habit you have that you're willing to admit?",
        "Do you have an inner monologue? Do you think your thoughts in words or concepts?",
        "What's a habit you picked up as a child that you wish you hadn't?",
        "What's one thing you wish you had known when you started your career?",
        "If you could pick up a new skill in an instant what would it be?",
        "What do you find yourself fantasizing about these days?",
        "What's one thing about you that hasn't changed in the last 10 years?",
        "What's one thing you do to distract yourself that you think you should less of?",
        "What's a truth you've recently come to terms with?",
        "Where do you see yourself professionally a year from now?",
        "What activity absorbs you completely and makes you lose track of time?",
        "What fictional character do you most relate to?",
        "What are you most proud of right now?",
        "What gives you supreme joy right now?",
        "What's something that tends to ruin your day as of late?",
        "If you were a dictator of a small country what crazy dictator things would you do?",
        "If you had to choose a theme song for your life what would it be?",
        "If you could choose one experience from your life that your child could also have what would it be?",
        "What's something you're looking forward to in the coming months?",
        "What’s is one thing we don’t know about you?",
        "What's a surprising hobby you enjoy?",
        "What's something that will never cease to make you laugh?",
        "Who has had the most positive impact on your life?",
        "What’s your best tip for staying focused and productive?",
        "What's a challenge you recently faced?",
        "You can go back in time and experience any historical event. Where do you go and when?",
        "How do you approach networking and have you had any success stories?",
        "What does <i>success</i> mean to you and how has that definition evolved over time?",
        "Are you settling for less than what you are worth? If so why?",
        "If you could live in any movie universe for a week which one would you pick?",
        "What kind of a day have you had so far today?",
        "What's one rule you'd put in place if you ruled the world for a day?",
        "What's a fear you've faced and overcome?",
        "Do you want to share a personal goal that you have?",
        "What's the most useless thing you've ever been taught in school?",
        "If you could create a new holiday what would it celebrate?",
        "Is there anything you think your generation does better than the next generation?",
        "What do you think is the most misunderstood aspect of your personality by others?",
        "Which form of self-expression has become increasingly important to you?",
        "What's currently worrying you?",
        "How do you show someone you care about them?",
        "If all animals were the same size what would win in a fight?",
        "What's a deep question you often ask yourself?",
        "What do you think is your biggest strength and your biggest weakness?",
        "What makes you optimistic about the future?",
        "What behavior or trait immediately makes you respect someone?",
        "What's a goal or project you've made progress on?",
        "What compliment would you give yourself right now?",
        "If you had the power to completely solve one social or political issue affecting the world today which would you choose?",
        "How has your perspective on the world changed in the last five years?",
        "What do you think people might envy you for?",
        "What would brighten your day today?",
        "What recent mistake taught you the most?",
        "What's your least favorite part of your job and why?",
        "What single event or decision do you think most affected the rest of your life? Was there a turning point in your life?",
        "How do you approach your overall wellness?",
        "When do you feel most helpful to others?",
        "Have you ever had a mentor and what was the most important thing they taught you?",
        "Where do you feel you're improving the most?",
        "In what ways do you mentor or support others in your field?",
        "If you had a magic wand how would your life magically be better a month from now?",
        "What one thing (something you made something you did something you contributed to) would you like to be remembered by?",
        "What's something you'd like to do but have a hard time acting on?",
        "What's your favorite article of clothing you own?",
        "What do you feel like you’re really good at?",
        "What scientific or technological advance blows your mind?",
        "What would people be surprised to learn you spend a lot of time on at work?",
        "Which best describes you? An introvert or an extrovert?",
        "Explain your current feelings in life to a 3 year old.",
        "What's something from your childhood that you think no one else could relate to?",
        "What's one thing you would change that's commonly taught to children today?",
        "What do you consider as red flags in a potential employee or coworker?",
        "You just became a new member of the Spice Girls. What's Spice name do you create for yourself?",
        "What's a recent moment in which you feel you represented yourself authentically?",
        "What's something expensive you splurge on that you believe is worth the money?",
        "Are you currently mentoring anyone or being mentored? How is that going?",
        "What area in your life are you looking to improve?",
        "What's the most significant risk you've taken in your career and how did it turn out?",
        "What do you think is the most important quality of human civiliation for its continued survival?",
        "What have you been eating lots of lately?",
        "What is the most powerful habit good or bad in your life right now?",
        "Looking back what's one decision you made that was a leap of faith? How did it shape where you are today?",
        "What do you think is the best place or way to meet a signifcant other?",
        "What title would you give to the current phase of your life?",
        "What legacy do you hope to leave as a result of your professional work?",
        "What's a recent personal growth moment you've experienced?",
        "What do you know isn't real but really wish it existed?",
        "What life event did you learn the most from? Would you change it?",
        "If you were an inanimate object what would you be and why?",
        "What instantly makes you think less of someone?",
        "What behavior or trait immediately makes you like someone?",
        "What's something you recently taught yourself?",
        "Which is more important nature or nurture?",
        "What does 'living authentically' mean to you and how do you practice it in your daily life?",
        "How do you reconcile the pursuit of your personal goals with the need to contribute to the community?",
        "What is an irrational fear you have?",
        "Do you believe in second chances?",
        "What's your favorite personality or character trait about yourself?",
        "What is the most fun you have had recently?",
        "What's your go-to productivity hack?",
        "What talent of yours do you consider to be inherent like an advantage you were born with?",
        "If you were in a zombie apocalypse and you could only choose 3 people would you be on your team?",
        "Is there anything you think your generation does better than the previous generation?",
        "What's a habit you'd like to adopt but find difficult to stick to?",
        "You can stop time for 24 hours. What do you do with this opportunity?",
        "How do you contribute to a positive work environment or culture?",
        "What kind of games did you play as a child?",
        "Who had the most significant impact on your career and why?",
        "If you could learn one secret from anyone who would it be and what would it pertain to?",
        "What's a current trend you find concerning?",
        "What's the best purchase you recently made?",
        "What were some of my most challenging learning moments in your career and what made them so?",
        "What is the one thing you've made that you're the most proud of?",
        "Do you feel challenged enough at work?",
        "What elements of your daily routine have become non-negotiable lately?",
        "If your life was a story what chapter would you currently be in and what would its title be?",
        "A surprise package arrives at your doorstep — it's from everyone here! What's inside?",
        "What does your dream home look like?",
        "If you had to give a TED Talk without any preparation what topic would you choose?",
        "If you had 9 lives what would you do with them?",
        "What's your most common feeling lately?",
        "A stranger is inhabiting your body for the day. What are some tips you’d give them?",
        "Is there something you wish everybody knew about you without you having to tell them?",
        "What's the weirdest food combination you actually enjoy?",
        "What's something you admire about each person here?",
        "What's something you came across recently that gave you hope or inspiration?",
        "What's one thing you're doing that could improve your life soon?",
        "What's an interesting conversation you had recently?",
        "What community do you currently feel the strongest connection to?",
        "What would you like to learn more about soon?",
        "What have you been dreaming of eating lately?",
        "What's one new and interesting thing you've been thinking about lately?",
        "What do you wish you had done differently recently?",
        "What's an interest of yours you’ve yet to act on?",
        "What's a conversation you haven't had but think you should?",
        "What without fail always makes you laugh?",
        "What's something you're looking forward to experiencing or doing?",
        "What's something you learned recently?",
        "What's something you wish people asked you about more often?",
        "What would you most like to become famous for?",
        "What's your favorite snack?",
        "Do you have any biases you're aware of?",
        "What actions if taken would make you proud of yourself regardless of the outcome?",
        "If you had a magic wand how would your life be better?",
        "What's the last thing you purchased?",
        "What's one thing you recently did for yourself?",
        "What's one thing you did recently that you're proud of?",
        "What's an unconventional piece of advice that has had a significant impact on your life?",
        "If you were perpetually surrounded by one aroma (asides your own natural scent) which you and everyone around you could smell what would it be?",
        "If you could intervene during any historic event changing history what would it be? How would things unfold differently?",
        "What's one topic you could talk about for hours right now?",
        "How do you prioritize your goals and desires in life?",
        "How do you feel about what you accomplished recently?",
        "What's that one thing you keep buying or doing even though you know it's unhealthy?",
        "What's one thing you do to distract yourself that you think you should do less of?",
        "What's the best meal you had recently?",
        "Is there anything important you've been putting off? If so why?",
        "What has surprised you recently?",
        "What advice would you give to your teenage self?",
        "How can you create an environment that will naturally bring about your currently desired change?",
        "What's the funniest thing you recently saw?",
        "What are three words you'd use to describe how you currently feel?",
        "What is the most trivial thing about which you have a strong opinion?",
        "What do you plan to learn in the coming days?",
        "What’s one thing that brings you energy and joy lately?",
        "If you could travel anywhere in the world right now where would you go and why?",
        "What's something you've been reminding yourself lately?",
        "Do you think you fit a particular stereotype? Which one and why?",
        "What’s one thing you hope to get accomplished soon?",
        "What’s one of your earliest memories of earning money?",
        "Where you currently facing uncertainty or unknown and how are you navigating it?",
        "What is one thing you wish you did recently but didn’t do?",
        "Thinking about your current #1 goal what makes you optimistic you'll achieve it?",
        "What's going well with work or school? What's not going well?",
        "Is there a particular event or moment that redirected the course of your life? How did it impact you?",
        "If you were reincarnated as an animal based on your personality what animal do you think you would come back as?",
        "What's your mantra lately?",
        "What did you fail at recently?",
        "What quality are you currently cultivating in yourself?",
        "What's the best thing that happened to you recently?",
        "What character trait instantly makes you respect someone?",
        "You just inherited $10000000. How does your life change tomorrow?",
        "If you had the power of perfect memory recall what’s the first memory you’d revisit?",
        "What is something you're terrible at but wish you could do well?",
        "What’s your strategy for professional growth?",
        "What is something you recently tried and loved?",
        "What is one thing you didn’t do so well recently?",
        "How have you been lately?",
        "What's a great piece of advice you recently received?",
        "What's a book or podcast you'd recommend that’s related to your career?",
        "What's a significant change you're considering or have made?",
        "What's the best advice you've ever received?",
        "What's the most useful thing you've ever been taught in school?",
        "What's a difficult conversation you recently had?",
        "Without saying what the category is what are your top five?",
        "What indulgence do you currently spend the most money on?",
        "What's something you recently learned?",
        "How can you take better care of yourself? How will you make that happen?",
        "What community do you currently feel the most connected to?",
        "What's a standout moment where you felt excited recently?",
        "How well do you feel your work aligns with your purpose or identity?",
        "What’s something you are really into right now?",
        "What aspects of how you were raised do you want to continue on to future generations? What aspects do you want to be sure not to repeat?",
        "Who's life do you think you've impacted the most?",
        "What would you title the most recent chapter of your life?",
        "Do you have any personal tradition?",
        "What's one thing you wish you talked about more?",
        "If you could have a superpower that helps you in your current job what would it be?",
        "What's your favorite way to unwind after a busy week?",
        "You're offered vast wealth extraordinary intellect renowned fame or stunning looks. Which do you choose?",
        "What's your most used item right now?",
        "What's a hobby you've always wanted to try?",
        "What aspects of life are you loving most right now?",
        "What is something you love that everyone else hates?",
        "What areas of personal development do you feel you need to focus on to to achieve further professional success?",
        "If you could witness any event from the past present or future what would it be and why?",
        "What song is 10/10 in your book but no one has heard of it?",
        "What's something you're you proud of but never have an excuse to talk about?",
        "What's one work-related skill you'd like to develop and why?",
        "What would you consider to be a 'dream job' and how close is your current job to that ideal?",
        "What is something you hate that everyone else loves?",
        "What are your best habits? How did you develop them?",
        "What's your favorite smell?",
        "How's your family doing?",
        "What's one thing you miss the most growing up as a kid?",
        "You will be granted supernatural ability in one of your five sense (sight smell taste hearing). Which would you choose and why?",
        "What would you like to thank yourself for right now?",
        "How do you stay productive and motivated when working from home?",
        "How would you describe your approach to your career so far?",
        "What are people surprised to learn you're really good at?",
        "How do you stay updated with the latest developments in your field?",
        "Think of someone you're currently in conflict with. If it was the last conversation you'd ever have with them what would you say?",
        "What's the most likely cause for the end of humanity and how do we stop it?",
        "What's your favorite lesson you've learned from a culture different from your own?",
        "What have you previously tolerated that you no longer allow in your life?",
        "Which childhood book or story influenced you the most?",
        "What outfit makes you feel powerful smart or capable?",
        "What's your favorite way to relax these days?",
        "What's something you're frequently complimented on?",
        "What’s your take on the common career advice to <i>follow your passion</i>",
        "Have you ever had an epiphany? What was it about and what sparked the realization?",
        "What's an ethical dilemma that keeps you up at night?",
        "Where do you wish you had grown up?",
        "What do you consider as red flags in a potential employer or boss?",
        "What's a recent disagreement or conflict you had in the workplace? How did you handle it?",
        "How would you summarize your last 12 months in one sentence?",
        "What would you do if there were no internet for the next 24 hours?",
        "What is a childhood habit or preference that you'll never outgrow?",
        "What's something you strongly believed in your childhood that you no longer feel sure about?",
        "What's a recent decision you're glad you made?",
        "What is something you've become increasingly interested in the more you've learned about it over time?",
        "What was the last fear you overcame and how?",
        "What did you recently fail at? What did you learn from it?",
        "What skill of yours are you most proud of?",
        "Can you share an unexpected goal you have for this year?",
        "What is the smallest thing for which you are grateful?",
        "What's a recent decision that was hard to make?",
        "Have you ever made a dramatic career shift and what drove that decision?",
        "How has your definition of happiness changed as you've gotten older?",
        "What's the best career advice you've ever received?",
        "Are human desires endless and can a society exist without wanting more?",
        "What is something you've done that you recommend everyone to do?",
        "Name one thing that stresses you out without fail.",
        "What's a new skill or knowledge you're learning right now?",
        "How has your perspective on work-life balance evolved over the years and what influences shaped this?",
        "Have any priorities recently shifted to the forefront of your life?",
        "Do you have any conspiracy theories? If so what are they?",
        "What's one thing that you wish would never happen to you?",
        "You get to invent something. What is it and what does it do?",
        "What would make you feel like <i>you made it</i>",
        "Which societal norm would you like to see ended and why? What changes would you propose?",
        "On a scale of 1 to 10 how valued do you feel at work?",
        "What's a significant professional challenge you overcame in the last year?",
        "If you were a pizza topping what would you be and why?",
        "What do you think all happy people have in common?",
        "What's something other people commonly do that you avoid and are proud of doing so?",
        "What public figure has had greatest impact on your personal life philosophy?",
        "What's a common myth about your profession that you can debunk?",
        "What tools or apps do you find indispensable for your work?",
        "How have you stepped out of your comfort zone recently?",
        "What traits in others are you attracted to?",
        "Before having a conversation with someone do you ever rehearse what you are going to say? Why",
        "What are some of your recent highlights and lowlights?",
        "If you could telepathically say something that all 8+ billion people on Earth could hear at once what would it be?",
        "What's some surprising feedback you recently received?",
        "How do you measure the impact of your work on society?",
        "What's a recent moment in which you're proud that you spoke up?",
        "What’s something that made you laugh recently?",
        "What was your first job ever?",
        "What's one thing you've never done but feels like it's something you need to do in your lifetime?",
        "What is your best advice on how to apologize?",
        "Imagine you could instill one habit in your child that they would carry for life. What habit would you choose and why?",
        "Do you feel you're operating in a sustainable way?",
        "Think of one of your big lofty goals. What small step could you take today towards achieving it?",
        "What do you wish people would talk more about right now?",
        "What's the most significant risk you've ever taken and how did it turn out?",
        "What song has been on repeat for you lately? Does it have any special meaning?",
        "What made you happy today?",
        "What was your first job and what did it teach you?",
        "What is your favorite word and why?",
        "What's your favorite quote and why?",
        "What is the quality you admire the most in the person you dislike the most?",
        "If you could only use five words how would you describe yourself?",
        "What professional accomplishment are you most proud of and why?",
        "If you had the power to talk to animals which species would you chat with first?",
        "You can only guarantee your child learns one life principle. What do you teach them?",
        "If you had $1M but couldn’t spend a penny of it on yourself what would you spend it on?",
        "What movie traumatized you as a kid?",
        "If every time you snapped your fingers you would instantly and irreversibly be transported to a random point in humanity's timeline would you snap your fingers? If so how often?",
        "What are 3 things you love about yourself?",
        "Is there a behavior or pattern you keep falling into that hurts yourself?",
        "You can guarantee that your child will have a deep understanding of one event in history. Which event do you choose and why?",
        "How do you think your profession will change in the future and how are you preparing for it?",
        "What's the most important life lesson you've learned in the last 10 years?",
        "Have you tried any new foods or restaurants lately?",
        "Is there anyone you envy? If so whom and for what?",
        "What is something you're coming to realize?",
        "What's something you're looking forward to doing or experiencing?",
        "What's your favorite object?",
        "What are you most grateful for in your life right now?",
        "What's a goal you're working towards?",
        "What’s one family tradition you want to pass down to your kids?",
        "What do you have up in your browser tabs right now?",
        "Explain your job to a 3 year old.",
        "You have to start a business. If you already have one it can't be your current one. What would you name it and what would it do?",
        "Have you attended any interesting work-related seminars or workshops lately?",
        "What's the most enjoyable project you've worked on recently?",
        "What is one your core principles in life that is guiding you at this time?",
        "What’s something at the top of your to-do list?",
        "What fact about yourself took you the longest to understand or accept?",
        "How well are you taking care of yourself lately?",
        "If you could level up any aspect of yourself (i.e. strength intelligence charisma etc.) but you had to decrease another aspect of yourself by the same amount what aspects would you level up and sacrifice?",
        "If you could start your own charity what would it focus on?",
        "What profession would you be in if you had known about it earlier?",
        "If the last month were a chapter of your life what would you title it?",
        "Is there anything you think the next generation will do better than your generation?",
        "In what ways do you think hardship can contribute to personal growth?",
        "What's something you've recently let go of and how has it impacted you?",
        "What's something very strange that happened to you?",
        "What's one piece of critical feedback you've received? How did you act on it?",
        "What thoughts distract you when you’re trying to get to sleep?",
        "What word describes your essence the best?",
        "What's something you wish you knew earlier about being a good colleague?",
        "Is there a quote or saying you call to mind often intentionally or unintentionally? ",
        "Have you ever desired or longed for something but once you got it discovered it was overrated or that you no longer wanted it?",
        "What trait signals to you that someone is wise?",
        "How has your perspective on your career changed over time?",
        "What’s a mantra or affirmation you resonate with right now?",
        "What's the most exciting improvement you've been seeing in yourself recently?",
        "What's an interesting conversation you recently had?",
        "What practice or habit (if anything) best supports your mental health/well-being?",
        "If you could be the CEO of any company what company would you choose?",
        "If you had to skip on meal every day for the rest of your life which meal would it be?",
        "Can you share an instance where your first impression of someone was completely wrong?",
        "What's something that you wish was easier for you?",
        "What's a great piece of advice you recently received?",
        "What's a new hobby or activity you've tried recently?",
        "If your life was a genre of music what would it be?",
        "What's something you're absolutely convinced is going to happen in the future?",
        "What's a fun project you've worked on recently?",
        "Do you have a best year of your life? A worst?",
        "Which superpower would you pick to subtly make your everyday life easier?",
        "What is your biggest accomplishment outside of academia and work?",
        "Is there anything you think the previous generation did better than your generation?",
        "What are you grateful for lately?",
        "What fictional character would you most like to have as a mentor?",
        "What's something you've been reminding yourself to think do or feel lately?",
        "What's one interesting thing you've been thinking about lately?",
        "In three words how would your family and friends describe you?",
        "Are you waiting on someone or something to progress in an aspect of your life?",
        "If you had one minute left to live what would you do?",
        "What's your favorite non valuable item you'll keep to the grave?",
        "Where were you born?",
        "What's something you're interested to learn more about?",
        "What's something that will make you smile every time?",
        "What subject or course do you wish they had offered in school?",
        "What's your biggest dream?",
        "What’s a new movie or show you've enjoyed recently?",
        "What do you wish people would ask you more about right now?",
        "Does your current job challenge you to grow in the ways you truly want? If not what’s missing?",
        "What trends do you foresee in your industry in the next five years?",
        "How well do you receive feedback?",
        "What's your secret talent that no one would expect you to have?",
        "If you could choose one superpower but it had to be extremely specific and unusual what would it be?",
        "What skills or passions are you not currently utilizing in your job?",
        "What's a memorable lesson you've learned from a mistake you've made?",
        "If you could use a time machine would you rather have one that only goes back in time or only goes forward?",
        "If you could know for certain the answer to any question what would that question be?",
        "The world needs more of my...",
        "What career decisions have you made based on fear? What decisions have been based on confidence?",
        "What is the most ordinary-seeming thing that you find fascinating?",
        "When you think of the legacy you want to leave does your current job contribute to that vision?",
        "What actions if taken would make you proud of yourself a month from now regardless of the outcome?",
        "What's a habit you're trying to develop or break?",
        "What is something that's easy for you but seems difficult for most other people?",
        "What’s your biggest flex in life right now?",
        "What's one of your biggest pet peeves?",
        "What's something you've achieved that you never thought possible for yourself?",
        "What's a major life decision you made that you're really happy about?",
        "On a scale of 1-10 how happy are you?",
        "What behavior or trait immediately makes you trust someone?",
        "How do you prioritize your tasks when everything seems urgent?",
        "Which superhero’s powers do you feel are underestimated?",
        "What are your biggest goals between now and the next issue of our Letterloop?",
        "What color describes your mood today?",
        "What are 3 words you'd used to describe how you currently feel?",
        "What's the most challenging thing you're working through these days?",
        "If you could be invisible but it would mean being permanently invisible would you want to be this way?",
        "If you could ask your future self one thing what would it be?",
        "What's one way in which you're completely different from yourself 10 years ago?",
        "When was the last time you experienced stillness and wonder?",
        "Is there an experience you think everyone should have at least once in their lives?",
        "What's been on your mind a lot lately?",
        "How did you spend your most recent weekend?",
        "What do people think is hard but actually isnt?",
        "What's something you currently doubt conciously or subconsciously that you can do?",
        "If you were a teacher what would you teach and what ages would your students be?",
        "What's an unpopular or controversial opinion that you hold?",
        "What is the last book you read? Would you recommend it?",
        "What is your most regretful purchase?",
        "If you could witness any event in the future what would you choose to see?",
        "If you only had one year left to live what would you do?",
        "What's something good that recently happened to you?",
        "What's the worst advice you've ever been given?",
        "You're given a sidekick with any superpower of your choosing. What's their name and what's their power?",
        "What first impression do you hope you make on people?",
        "What stopped you from following or encouraged you to follow your childhood passion?",
        "What's a situation that tested your resilience?",
        "Has your gut feeling or intuition about someone or something ever been wrong?",
        "What's a professional setback or shortfall you recently experienced and how has it influenced you?",
        "What’s your dream vacation right now? Why?",
        "How has your industry changed since you started your career?",
        "What's something you could talk about for hours right now?",
        "What self-limiting beliefs do you currently hold?",
        "What trait do you admire?",
        "What are the top three qualities of your ideal colleague?",
        "What's a difficult conversation you've been meaning to have?",
        "If seasons never changed which would you most like to live in eternally?",
        "What do you most need to hear right now and from whom?",
        "What is something other people admire about you?",
        "How do you think you'll be completely different from yourself 10 years from now?",
        "What's the best lesson you've learned from a difficult situation?",
        "What's the most unusual food you've ever tried and would you eat it again?",
        "What's a skill you use at work that you also use in your personal life?",
        "If you had to get a tail what tail would you want and what would you use it for?",
        "What's something you recently came across that gave you hope or inspiration?",
        "What's something you did recently that took courage?",
        "What's a movie you can watch over and over without ever getting tired of?",
        "What do you think is the most significant impact individuals can make in the world today?",
        "What is the most memorable meal you've ever had? (It can be good or bad.) What made it so memorable?",
        "What's your philosophy in life?",
        "What's a common piece of advice you disagree with and why?",
        "How do you describe your current job to someone who's not in your industry?",
        "Is there any proffesional breakthrough in your career?",
        "What's your earliest memory?",
        "What is your best season of the year? Why?",
        "What was your favorite childhood toy?",
        "If you could promote one value or ethic in the world what would it be and why do you think it's vital?",
        "Is there anything you would say to yourself in your early 20s?",
        "What is one action that would make today a success?",
        "Given the choice of anyone in the world whom would you want as a dinner guest?",
        "If you could go back and relive one day in your life without changing anything about it which day would you choose?",
        "What advice do you wish you'd received earlier?",
        "You can go back in time for 5 minutes. What would you do?",
        "What's the best advice you've ever given someone?",
        "What's the most important lesson you've learned about leadership?",
        "What person in your life do you most admire?",
        "What do you think will still be the same about you 10 years from now?",
        "Have you been to any cool places lately?",
        "Are you known for having a personal catchphrase or something you say often?"
    ];

    function getRandomQuestion() {
        const randomIndex = Math.floor(Math.random() * questions.length);
        return questions[randomIndex];
    }

    const questionBox = document.getElementById("question-box");
    questionBox.textContent = getRandomQuestion();

    const calmColors = [
        "#E3F2FD", // light blue
        "#FFEBEE", // soft pink
        "#E8F5E9", // soft green
        "#FFF3E0", // light orange
        "#F3E5F5", // lavender
        "#E0F7FA", // light cyan
        "#FFFDE7"  // pale yellow
    ];

    function getRandomBackgroundColor() {
        const randomIndex = Math.floor(Math.random() * calmColors.length);
        return calmColors[randomIndex];
    }

    document.body.style.backgroundColor = getRandomBackgroundColor();
});
